Verify that TMPDIR can hold executables before installing
This detects when `/tmp` has been mounted with "noexec" mode and avoids
the cryptic error:

  ./configure: Permission denied

Hopefully the information provided will be enough for the user to know
that they have to change TMPDIR to another location.

diff --git a/bin/ruby-build b/bin/ruby-build
--- a/bin/ruby-build
+++ b/bin/ruby-build
@@ -1016,8 +1016,20 @@ else
   TMP="${TMPDIR%/}"
 fi
 
-if [ ! -w "$TMP" ] || [ ! -x "$TMP" ]; then
+# Check if TMPDIR is accessible and can hold executables.
+tmp_executable="${TMP}/ruby-build-test.$$"
+noexec=""
+if mkdir -p "$TMP" && touch "$tmp_executable" 2>/dev/null; then
+  cat > "$tmp_executable" <<<"#!$BASH"
+  chmod +x "$tmp_executable"
+else
   echo "ruby-build: TMPDIR=$TMP is set to a non-accessible location" >&2
+  exit 1
+fi
+"$tmp_executable" 2>/dev/null || noexec=1
+rm -f "$tmp_executable"
+if [ -n "$noexec" ]; then
+  echo "ruby-build: TMPDIR=$TMP cannot hold executables (partition possibly mounted with \`noexec\`)" >&2
   exit 1
 fi
 
