Require Java 7 for jruby-9000-dev.

diff --git a/bin/ruby-build b/bin/ruby-build
--- a/bin/ruby-build
+++ b/bin/ruby-build
@@ -576,6 +576,23 @@ fix_rbx_irb() {
     true
 }
 
+require_java7() {
+  local version=`java -version 2>&1`
+  if [ $? -eq 0 ]
+  then
+    if [[ $version == *1.[78]* ]]
+    then
+      return 0
+    else
+      echo "jruby-9000-dev requires Java 7 - please install a 1.7 compatible JRE, or ensure it is on your path"
+      return 1
+    fi
+  else
+    echo "Couldn't execute Java - please install a 1.7 compatible JRE, or ensure it is on your path"
+    return 1
+  fi
+}
+
 require_gcc() {
   local gcc="$(locate_gcc || true)"
 
