Change Error message for missing subversion
The current error message for missing subversion is "error: please install \`svn\` and try again", leading the user to try to find and install a package named "svn" (eg. `aptitude install svn for # debian / ubuntu). Changing it to "subversion" can help users unaware that svn is a binary installed by the subversion package, get through the error.

diff --git a/bin/ruby-build b/bin/ruby-build
--- a/bin/ruby-build
+++ b/bin/ruby-build
@@ -419,7 +419,7 @@ fetch_svn() {
   if type svn &>/dev/null; then
     svn co -r "$svn_rev" "$svn_url" "${package_name}" >&4 2>&1
   else
-    echo "error: please install \`svn\` and try again" >&2
+    echo "error: please install Subversion and try again" >&2
     exit 1
   fi
 }
