Allow overriding HTTP client type based on environment variable `RUBY_BUILD_HTTP_CLIENT` (pyenv/pyenv#1126)

diff --git a/bin/ruby-build b/bin/ruby-build
--- a/bin/ruby-build
+++ b/bin/ruby-build
@@ -304,16 +304,22 @@ http() {
   local file="$3"
   [ -n "$url" ] || return 1
 
-  if type aria2c &>/dev/null; then
-    "http_${method}_aria2c" "$url" "$file"
-  elif type curl &>/dev/null; then
-    "http_${method}_curl" "$url" "$file"
-  elif type wget &>/dev/null; then
-    "http_${method}_wget" "$url" "$file"
+  local http_client
+  if [ -n "${RUBY_BUILD_HTTP_CLIENT}" ]; then
+    http_client="http_${method}_${RUBY_BUILD_HTTP_CLIENT}"
   else
-    echo "error: please install \`aria2c\`, \`curl\` or \`wget\` and try again" >&2
-    exit 1
+    if type aria2c &>/dev/null; then
+      http_client="http_${method}_aria2c"
+    elif type curl &>/dev/null; then
+      http_client="http_${method}_curl"
+    elif type wget &>/dev/null; then
+      http_client="http_${method}_wget"
+    else
+      echo "error: please install \`aria2c\`, \`curl\` or \`wget\` and try again" >&2
+      exit 1
+    fi
   fi
+  "${http_client}" "$url" "$file"
 }
 
 http_head_aria2c() {
