Fix version check for Java 17
* Fixes https://github.com/rbenv/ruby-build/issues/1798
* OpenJDK 17 reports:
  $ java -version
  openjdk version "17" 2021-09-14
  There is no dot in the version, so we need to only use the first match from grep -o.
* Clarify it is a minimum required java version, not an exact version.

diff --git a/bin/ruby-build b/bin/ruby-build
--- a/bin/ruby-build
+++ b/bin/ruby-build
@@ -854,8 +854,8 @@ fix_rbx_irb() {
 require_java() {
   local required="$1"
   local java_version="$(java -version 2>&1)"
-  local version_string="$(grep 'java version' <<<"$java_version" | head -1 | grep -o '[0-9.]\+' || true)"
-  [ -n "$version_string" ] || version_string="$(grep 'openjdk version' <<<"$java_version" | head -1 | grep -o '[0-9.]\+' || true)"
+  local version_string="$(grep 'java version' <<<"$java_version" | head -1 | grep -o '[0-9.]\+' | head -1 || true)"
+  [ -n "$version_string" ] || version_string="$(grep 'openjdk version' <<<"$java_version" | head -1 | grep -o '[0-9.]\+' | head -1 || true)"
   IFS="."
   local nums=($version_string)
   IFS="$OLDIFS"
@@ -863,7 +863,7 @@ require_java() {
   [ "$found_version" -gt 1 ] 2>/dev/null || found_version="${nums[1]}"
   [ "$found_version" -ge "$required" ] 2>/dev/null && return 0
   colorize 1 "ERROR" >&3
-  echo ": Java ${required} required, but your Java version was:" >&3
+  echo ": Java >= ${required} required, but your Java version was:" >&3
   cat <<<"$java_version" >&3
   return 1
 }
