Extract has_checksum_support predicate function
- Remove unnecessary HAS_X_SUPPORT variables
- Merge conditional for unsetting mirror-url
- Memoize has_checksum_support function

diff --git a/bin/ruby-build b/bin/ruby-build
--- a/bin/ruby-build
+++ b/bin/ruby-build
@@ -246,6 +246,12 @@ compute_md5() {
   fi
 }
 
+declare -a HAS_CHECKSUM_SUPPORT
+has_checksum_support() {
+  local checksum_command="$1"
+  return ${HAS_CHECKSUM_SUPPORT[$checksum_command]:=$(echo test | "$checksum_command" >/dev/null; echo $?)}
+}
+
 verify_checksum() {
   local checksum_command
   local filename="$1"
@@ -255,21 +261,18 @@ verify_checksum() {
   [ -e "$filename" ] || return 0
 
   case "${#expected_checksum}" in
-  0) # If there's no expected checksum, return success
-    return 0
-    ;;
-  32) # MD5
-    [ -n "$HAS_MD5_SUPPORT" ] || return 0
-    checksum_command="compute_md5"
-    ;;
-  64) # SHA2 256
-    [ -n "$HAS_SHA2_SUPPORT" ] || return 0
-    checksum_command="compute_sha2"
-    ;;
-  *) # unknown checksum algorithm, return failure
-    return 1
-    ;;
+  # If expected checksum is empty, return success
+  0) return 0 ;;
+  # MD5
+  32) checksum_command="compute_md5" ;;
+  # SHA2 256
+  64) checksum_command="compute_sha2" ;;
+  # unknown checksum algorithm, return failure
+  *) return 1 ;;
   esac
+
+  # If chosen provided checksum algorithm isn't supported, return success
+  has_checksum_support "$checksum_command" || return 0
 
   # If the computed checksum is empty, return failure
   local computed_checksum=`echo "$($checksum_command < "$filename")" | tr [A-Z] [a-z]`
@@ -1225,21 +1228,8 @@ else
   RUBY_BUILD_DEFAULT_MIRROR=
 fi
 
-if [ -n "$RUBY_BUILD_SKIP_MIRROR" ]; then
+if [ -n "$RUBY_BUILD_SKIP_MIRROR" ] || ! has_checksum_support compute_sha2; then
   unset RUBY_BUILD_MIRROR_URL
-fi
-
-if echo test | compute_sha2 >/dev/null; then
-  HAS_SHA2_SUPPORT=1
-else
-  unset HAS_SHA2_SUPPORT
-  unset RUBY_BUILD_MIRROR_URL
-fi
-
-if echo test | compute_md5 >/dev/null; then
-  HAS_MD5_SUPPORT=1
-else
-  unset HAS_MD5_SUPPORT
 fi
 
 SEED="$(date "+%Y%m%d%H%M%S").$$"
