ruby-package

diff --git a/bin/ruby-package b/bin/ruby-package
--- a/bin/ruby-package
+++ b/bin/ruby-package
@@ -1,10 +1,6 @@
 #!/usr/bin/env bash
 set -e
 
-package_platform() {
-  echo "$(uname -m)-$(uname -s)" | tr '[A-Z] ' '[a-z]_'
-}
-
 resolve_link() {
   $(type -p greadlink readlink | head -1) $1
 }
@@ -24,80 +20,28 @@ abs_dirname() {
 }
 
 usage() {
-  echo "usage: ruby-package [-v | --verbose] [--resume] DEFINITION"
+  echo "usage: ruby-package <command> [<args>]" >&2
   exit 1
 }
 
-bin_root="$(abs_dirname "$0")"
+bin_dir="$(abs_dirname "$0")"
+export PATH="${bin_dir}/../libexec:${bin_dir}:$PATH"
 
-verbose=""
-resume=""
+command="$1"
+command_path="$(command -v ruby-package-"$1" || true)"
 
-while :; do
-  case "$1" in
-    "-v" | "--verbose" )
-      verbose="-v"
-      shift
-      ;;
-    "--resume" )
-      resume=1
-      shift
-      ;;
-    "-"* )
-      usage
-      ;;
-    * )
-      break
-      ;;
-  esac
-done
+if [ -z "$TMPDIR" ]; then
+  export TMPDIR="/tmp"
+else
+  export TMPDIR="${TMPDIR%/}"
+fi
 
-definition="$1"
-if [ -z "$definition" ]; then
+if [ -z "$command" ]; then
+  usage
+elif [ -z "$command_path" ]; then
+  echo "ruby-package: ${command}: command not found" >&2
   usage
 fi
 
-package="${definition##*/}"
-prefix="/tmp/ruby-build/-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------/$package"
-
-package_dir="${package}.$(package_platform)"
-
-if [ -z "$resume" ]; then
-  "${bin_root}/ruby-build" $verbose "$definition" "$prefix"
-fi
-
-cwd="$(pwd)"
-cd "${prefix}/.."
-
-mkdir -p "${package_dir}/bin"
-cp "${bin_root}/../share/ruby-package/ruby-package-install" "${package_dir}/bin"
-cp "${bin_root}/../share/ruby-package/ruby-package-rewrite-text" "${package_dir}/bin"
-cc -Wall "${bin_root}/../share/ruby-package/ruby-package-rewrite-binary.c" -o "${package_dir}/bin/ruby-package-rewrite-binary"
-
-mkdir -p "${package_dir}/metadata"
-echo -n "$prefix" > "${package_dir}/metadata/prefix"
-echo -n "$package" > "${package_dir}/metadata/package"
-
-cd "$package"
-
-while read line; do
-  binary="${line#Binary file }"
-  if [ "$line" = "$binary" ]; then
-    # plain text match
-    text="${line%%:*}"
-    echo "$text" >> "../${package_dir}/metadata/text-files"
-  else
-    # binary match
-    binary="${binary% matches}"
-    echo "$binary" >> "../${package_dir}/metadata/binary-files"
-  fi
-done < <( grep -m 1 -R "$prefix" * )
-
-tar cf "../${package_dir}/package.tar" *
-
-cd ..
-
-tar czf "${cwd}/${package_dir}.rubypackage" "$package_dir"
-rm -fr "$package_dir"
-
-echo "${package_dir}.rubypackage"
+shift
+exec "$command_path" "$@"
