Enable users to discover how to update the ruby-build plugin

diff --git a/bin/ruby-build b/bin/ruby-build
--- a/bin/ruby-build
+++ b/bin/ruby-build
@@ -1199,6 +1199,10 @@ list_definitions() {
       [ -d "$DEFINITION_DIR" ] && ls "$DEFINITION_DIR"
     done
   } | sort_versions | uniq
+  {
+    echo "Can't find the version you want? Run:"
+    echo "rbenv install how-do-i-update-my-rbenv-build-plugin"
+  } >&2
 }
 
 sort_versions() {
